export const SET_FIELD_CROP_REPORTING = Symbol("SET_FIELD_CROP_REPORTING");
export const SET_INVESTOR_CONTRIBUTION_REPORTING = Symbol("SET_INVESTOR_CONTRIBUTION_REPORTING");
export const SET_SUMMARY_RESULTS_REPORTING = Symbol("SET_SUMMARY_RESULTS_REPORTING");