export const SET_PROJECTS = Symbol("SET_PROJECTS");
export const SET_PROJECTS_DROPDOWN = Symbol("SET_PROJECTS_DROPDOWN");
export const SET_PAGINATION = Symbol("SET_PAGINATION");
export const SET_PROJECTS_DROPDOWN_PAGINATION = Symbol(
  "SET_PROJECTS_DROPDOWN_PAGINATION"
);
export const SET_TOTAL_HECTARES = Symbol("SET_TOTAL_HECTARES");

export const SET_SELECTED_PROJECT = Symbol("SET_SELECTED_PROJECT");
export const CLEAR_SELECTED_PROJECT = Symbol("CLEAR_SELECTED_PROJECT");

export const SET_RESULT = Symbol("SET_RESULT");

export const SET_ERROR = Symbol("SET_ERROR");
export const SET_ERROR_DROPDOWN = Symbol("SET_ERROR_DROPDOWN");

export const START_PROCESSING = Symbol("START_PROCESSING");
export const STOP_PROCESSING = Symbol("STOP_PROCESSING");
export const START_PROCESSING_DROPDOWN = Symbol("START_PROCESSING_DROPDOWN");
export const STOP_PROCESSING_DROPDOWN = Symbol("STOP_PROCESSING_DROPDOWN");
